### ISSUE TITLE
Installation Instructions for Raspberry pi?

### ISSUE THREAD

**Issue by Charles-Ngg** [mayeaux/nodetube#193]
I try to run "docker-compose build" and it try to download node-sass from "https://github.com/sass/node-sass/releases/download/v4.13.1/linux-arm-64_binding.node"
which is does't exist.
It there installation Instructions for Raspberry pi?
thx

**Comment by mayeaux** [comment]
I've never tried to install NodeTube on a Raspberry Pi before but it's a very cool concept. Maybe open this as an issue in the `node-sass` and tag this issue and I will try and keep an eye on it? Thanks!

**Comment by Charles-Ngg** [comment]
looks like we can build node-sass on pi,I try to run "npm install " :

```
pi@raspberrypi:~/Downloads/nodetube $ npm install
npm WARN npm npm does not support Node.js v10.15.2
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
npm WARN npm You can find the latest version at https://nodejs.org/

> NodeTube@1.0.0 postinstall /home/pi/Downloads/nodetube
> node ./copySettingsAndPrivateFiles.js

Copying settings and private file if necessary
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.2 (node_modules/mocha/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.2: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"arm"})

up to date in 30.323s

```
It looks ok I guess?
then I try run "npm start": 

```
pi@raspberrypi:~/Downloads/nodetube $ npm start
npm WARN npm npm does not support Node.js v10.15.2
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
npm WARN npm You can find the latest version at https://nodejs.org/

> NodeTube@1.0.0 start /home/pi/Downloads/nodetube
> node --max-old-space-size=4096 app.js

node[29396]: ../src/node_platform.cc:414:std::shared_ptr<node::PerIsolatePlatformData> node::NodePlatform::ForIsolate(v8::Isolate*): Assertion `data' failed.
Aborted
npm ERR! code ELIFECYCLE
npm ERR! errno 134
npm ERR! NodeTube@1.0.0 start: `node --max-old-space-size=4096 app.js`
npm ERR! Exit status 134
npm ERR!
npm ERR! Failed at the NodeTube@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/pi/.npm/_logs/2020-03-12T02_00_17_868Z-debug.log
```
"npm run dev":
```
pi@raspberrypi:~/Downloads/nodetube $ npm run dev
npm WARN npm npm does not support Node.js v10.15.2
npm WARN npm You should probably upgrade to a newer version of node as we
npm WARN npm can't make any promises that npm will work with this version.
npm WARN npm Supported releases of Node.js are the latest release of 4, 6, 7, 8, 9.
npm WARN npm You can find the latest version at https://nodejs.org/

> NodeTube@1.0.0 dev /home/pi/Downloads/nodetube
> nodemon -e pug,js app.js

[nodemon] 1.19.4
[nodemon] to restart at any time, enter `rs`
[nodemon] watching dir(s): *.*
[nodemon] watching extensions: pug,js
[nodemon] starting `node app.js`
BOOTING APP...

NODE_ENV: development

RUNNING WITH THIS MANY PROCESSES: 1

SAVE AND SERVE FILES DIRECTORY: ./uploads

CACHING IS ON
CACHING IS RUNNING AGAINST: mongodb://localhost:27017/nodetube

CONNECTING TO REDIS, HOST: 127.0.0.1, PORT: 6379

CACHE RECENT INTERVAL IN MINUTES: 1
CACHE INTERVAL IN MINUTES: 5

UPLOADS ON: true

UPLOAD SERVER: /uploads

DOMAIN NAME AND TLD: https://nodetube.live

FRONTEND SERVER:

CACHING LOGS WILL NOT COME THROUGH

{ Error: Trying to open unclosed connection.
    at NativeConnection.Connection._handleOpenArgs (/home/pi/Downloads/nodetube/node_modules/mongoose/lib/connection.js:214:11)
    at NativeConnection.<anonymous> (/home/pi/Downloads/nodetube/node_modules/mongoose/lib/connection.js:309:37)
    at NativeConnection.deprecated [as open] (internal/util.js:66:15)
    at Mongoose.connect (/home/pi/Downloads/nodetube/node_modules/mongoose/lib/index.js:268:47)
    at /home/pi/Downloads/nodetube/app.js:123:14
    at Object.<anonymous> (/home/pi/Downloads/nodetube/app.js:413:5)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:743:3) state: 2 }
%s MongoDB connection error. Please make sure MongoDB is running.
[nodemon] clean exit - waiting for changes before restart
^Cpi@raspberrypi:~/Downloads/nodetube $ mon
mongo           mongodump       mongofiles      mongooplog      mongorestore    mongosniff      mongotop
mongod          mongoexport     mongoimport     mongoperf       mongos          mongostat       monitor-sensor
pi@raspberrypi:~/Downloads/nodetube $ mongo -v
ERROR: unrecognised option '-v'

MongoDB shell version: 2.4.14
usage: mongo [options] [db address] [file names (ending in .js)]
db address can be:
  foo                   foo database on local machine
  192.169.0.5/foo       foo database on 192.168.0.5 machine
  192.169.0.5:9999/foo  foo database on 192.168.0.5 machine on port 9999
options:
  --shell                               run the shell after executing files
  --nodb                                don't connect to mongod on startup - no
                                        'db address' arg expected
  --norc                                will not run the ".mongorc.js" file on
                                        start up
  --quiet                               be less chatty
  --port arg                            port to connect to
  --host arg                            server to connect to
  --eval arg                            evaluate javascript
  -u [ --username ] arg                 username for authentication
  -p [ --password ] arg                 password for authentication
  --authenticationDatabase arg          user source (defaults to dbname)
  --authenticationMechanism arg (=MONGODB-CR)
                                        authentication mechanism
  -h [ --help ]                         show this usage information
  --version                             show version information
  --verbose                             increase verbosity
  --ipv6                                enable IPv6 support (disabled by
                                        default)
  --ssl                                 use SSL for all connections
  --sslCAFile arg                       Certificate Authority for SSL
  --sslPEMKeyFile arg                   PEM certificate/key file for SSL
  --sslPEMKeyPassword arg               password for key in PEM file for SSL

file names: a list of files to run. files have to end in .js and will exit after unless --shell is specified
pi@raspberrypi:~/Downloads/nodetube $ sudo systemctl status mongodb.service
● mongodb.service - An object/document-oriented database
   Loaded: loaded (/lib/systemd/system/mongodb.service; enabled; vendor preset: enabled)
   Active: active (running) since Wed 2020-03-11 14:49:36 HKT; 19h ago
     Docs: man:mongod(1)
 Main PID: 385 (mongod)
    Tasks: 11 (limit: 4915)
   Memory: 55.9M
   CGroup: /system.slice/mongodb.service
           └─385 /usr/bin/mongod --config /etc/mongodb.conf

Mar 11 14:49:36 raspberrypi systemd[1]: Started An object/document-oriented database.
Mar 11 14:49:39 raspberrypi mongod[385]: all output going to: /var/log/mongodb/mongodb.log
```

**Comment by Charles-Ngg** [comment]
Raspbian (32bit) only have a version v2.4.14 mongo, I will try install nodetube on Ubuntu for Raspberry Pi when I have time.

**Comment by mayeaux** [comment]
It looks though like if you can connect to Mongo properly via Mongoose you will be off and running.

Not sure about ffmpeg though you may run into an issue there, worth looking into, let me know how it goes thanks!

**Comment by Charles-Ngg** [comment]
Hi,I have successfully install and run nodetube on my pi 4 with Ubuntu OS. 

There some notes,may help you for install npm and mongo:

    Install latest NodeJS on Ubuntu ARM
    https://gist.github.com/ted-piotrowski/33d7a23ce9f67231620d8edd825bf89e


mongodb :

    MongoDB 4.2.x (64-bit) on Raspberry Pi 4
    https://pimylifeup.com/mongodb-raspberry-pi/

    MongoDB - shutting down with code:62
    https://stackoverflow.com/questions/47850004/mongodb-shutting-down-with-code62

    Where is mongo database folder on the filesystem
    https://askubuntu.com/questions/982673/where-is-mongo-database-folder-on-the-filesystem

    MongoDB – Failed to unlink socket file /tmp/mongodb-27017
    https://mkyong.com/mongodb/mongodb-failed-to-unlink-socket-file-tmpmongodb-27017/
