### ISSUE TITLE
error on master

### ISSUE THREAD

**Issue by chovy** [mayeaux/nodetube#312]
```
odetube | Error: Cannot find module 'get-video-duration'
nodetube | Require stack:
nodetube | - /app/lib/mediaBrowsing/helpers.js
nodetube | - /app/controllers/frontend/account.js
nodetube | - /app/routes.js
nodetube | - /app/app.js
nodetube |     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:980:15)
nodetube |     at Function.Module._load (internal/modules/cjs/loader.js:862:27)
nodetube |     at Module.require (internal/modules/cjs/loader.js:1042:19)
nodetube |     at require (internal/modules/cjs/helpers.js:77:18)
nodetube |     at Object.<anonymous> (/app/lib/mediaBrowsing/helpers.js:3:39)nodetube |     at Module._compile (internal/modules/cjs/loader.js:1156:30)
nodetube |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
nodetube |     at Module.load (internal/modules/cjs/loader.js:1000:32)nodetube |     at Function.Module._load (internal/modules/cjs/loader.js:899:14)
nodetube |     at Module.require (internal/modules/cjs/loader.js:1042:19)
nodetube |     at require (internal/modules/cjs/helpers.js:77:18)nodetube |     at Object.<anonymous> (/app/controllers/frontend/account.js:19:38)
nodetube |     at Module._compile (internal/modules/cjs/loader.js:1156:30)
nodetube |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)nodetube |     at Module.load (internal/modules/cjs/loader.js:1000:32)
nodetube |     at Function.Module._load (internal/modules/cjs/loader.js:899:14)
nodetube |     at Module.require (internal/modules/cjs/loader.js:1042:19)nodetube |     at require (internal/modules/cjs/helpers.js:77:18)
nodetube |     at Object.<anonymous> (/app/routes.js:17:35)
nodetube |     at Module._compile (internal/modules/cjs/loader.js:1156:30)nodetube |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
nodetube |     at Module.load (internal/modules/cjs/loader.js:1000:32)
nodetube |     at Function.Module._load (internal/modules/cjs/loader.js:899:14)nodetube |     at Module.require (internal/modules/cjs/loader.js:1042:19)
nodetube |     at require (internal/modules/cjs/helpers.js:77:18)
nodetube |     at /app/app.js:92:20nodetube |     at Object.<anonymous> (/app/app.js:417:5)
nodetube |     at Module._compile (internal/modules/cjs/loader.js:1156:30)
nodetube |     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
nodetube |     at Module.load (internal/modules/cjs/loader.js:1000:32)
nodetube |     at Function.Module._load (internal/modules/cjs/loader.js:899:14)
```

**Comment by mr-winson** [comment]
Confirming this happens, just verifying problem as a second person.

**Comment by carlostojal** [comment]
Hey @chovy . Have you tried running "npm install"? This module was added about 2 months ago, and it is not used every time, only when a specific video doesn't have its duration in the database. So probably you never had this module installed but for some reason you need it now.
Try that and give feedback.

**Comment by mayeaux** [comment]
Just tried a fresh install and it worked fine
