### ISSUE TITLE
cannot install nodetube. Exception while  npm install

### ISSUE THREAD

**Issue by Adi-18** [mayeaux/nodetube#477]
- Fresh install of debian 10 (because of not running of MongoDB  on newer version) om proxmox as VM.
- apt-get update && apt-get upgrade -y
- apt install git lsb-release curl gpg redis gnupg ffmpeg net-tools nodejs npm -y
- node -v => v10.24.0
- npm -v => 5.8.0
- dpkg --print-architecture => amd64
- lsb_release -a
> No LSB modules are available.
> Distributor ID: Debian
> Description:    Debian GNU/Linux 10 (buster)
> Release:        10
> Codename:       buster
- npm install ==> error

While install message, that "npm does not support Node.js v10.24.0"
so:
- apt-get remove nodejs
- curl -fsSL https://deb.nodesource.com/setup_current.x | bash -
- apt-get install nodejs -y
- node -v => v21.6.1
- npm -v => 10.2.4
- npm install ==> error

While install message that "New minor version of npm available! 10.2.4 -> 10.4.0" "Run npm install -g npm@10.4.0 to update!"
so:
- npm install -g npm@10.4.0
- npm -v => 10.4.0
- npm install ==> error

Tail of output:
tones if depricadet
> npm WARN deprecated nodemailer@3.1.8: All versions below 4.0.1 of Nodemailer are deprecated. See https://nodemailer.com/status/
> npm WARN deprecated tar@2.2.2: This version of tar is no longer supported, and will not receive security updates. Please upgrade asap.
> npm WARN deprecated sinon@2.4.1: 16.1.1
> npm WARN deprecated core-js@2.6.11: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.
> npm WARN cleanup Failed to remove some directories [
> npm WARN cleanup   [
> npm WARN cleanup     '/home/nodetube/nodetube/node_modules/ngrok',
> npm WARN cleanup     [Error: ENOTEMPTY: directory not empty, rmdir '/home/nodetube/nodetube/node_modules/ngrok/bin'] {
> npm WARN cleanup       errno: -39,
> npm WARN cleanup       code: 'ENOTEMPTY',
> npm WARN cleanup       syscall: 'rmdir',
> npm WARN cleanup       path: '/home/nodetube/nodetube/node_modules/ngrok/bin'
> npm WARN cleanup     }
> npm WARN cleanup   ],
> npm WARN cleanup   [
> npm WARN cleanup     '/home/nodetube/nodetube/node_modules',
> npm WARN cleanup     [Error: ENOTEMPTY: directory not empty, rmdir '/home/nodetube/nodetube/node_modules/ngrok/bin'] {
> npm WARN cleanup       errno: -39,
> npm WARN cleanup       code: 'ENOTEMPTY',
> npm WARN cleanup       syscall: 'rmdir',
> npm WARN cleanup       path: '/home/nodetube/nodetube/node_modules/ngrok/bin'
> npm WARN cleanup     }
> npm WARN cleanup   ]
> npm WARN cleanup ]
> npm ERR! code 1
> npm ERR! path /home/nodetube/nodetube/node_modules/node-sass
> npm ERR! command failed
> npm ERR! command sh -c node scripts/build.js
> npm ERR! Building: /usr/bin/node /home/nodetube/nodetube/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
> npm ERR! gyp info it worked if it ends with ok
> npm ERR! gyp verb cli [
> npm ERR! gyp verb cli   '/usr/bin/node',
> npm ERR! gyp verb cli   '/home/nodetube/nodetube/node_modules/node-gyp/bin/node-gyp.js',
> npm ERR! gyp verb cli   'rebuild',
> npm ERR! gyp verb cli   '--verbose',
> npm ERR! gyp verb cli   '--libsass_ext=',
> npm ERR! gyp verb cli   '--libsass_cflags=',
> npm ERR! gyp verb cli   '--libsass_ldflags=',
> npm ERR! gyp verb cli   '--libsass_library='
> npm ERR! gyp verb cli ]
> npm ERR! gyp info using node-gyp@3.8.0
> npm ERR! gyp info using node@21.6.1 | linux | x64
> npm ERR! gyp verb command rebuild []
> npm ERR! gyp verb command clean []
> npm ERR! gyp verb clean removing "build" directory
> npm ERR! gyp verb command configure []
> npm ERR! gyp verb check python checking for Python executable "python2" in the PATH
> npm ERR! gyp verb `which` succeeded python2 /usr/bin/python2
> npm ERR! gyp verb check python version `/usr/bin/python2 -c "import sys; print "2.7.16
> npm ERR! gyp verb check python version .%s.%s" % sys.version_info[:3];"` returned: %j
> npm ERR! gyp verb get node dir no --target version specified, falling back to host node version: 21.6.1
> npm ERR! gyp verb command install [ '21.6.1' ]
> npm ERR! gyp verb install input version string "21.6.1"
> npm ERR! gyp verb install installing version: 21.6.1
> npm ERR! gyp verb install --ensure was passed, so won't reinstall if already installed
> npm ERR! (node:12937) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
> npm ERR! (Use `node --trace-deprecation ...` to show where the warning was created)
> npm ERR! gyp verb install version is already installed, need to check "installVersion"
> npm ERR! gyp verb got "installVersion" 9
> npm ERR! gyp verb needs "installVersion" 9
> npm ERR! gyp verb install version is good
> npm ERR! gyp verb get node dir target node version installed: 21.6.1
> npm ERR! gyp verb build dir attempting to create "build" dir: /home/nodetube/nodetube/node_modules/node-sass/build
> npm ERR! gyp verb build dir "build" dir needed to be created? /home/nodetube/nodetube/node_modules/node-sass/build
> npm ERR! gyp verb build/config.gypi creating config file
> npm ERR! gyp verb build/config.gypi writing out config file: /home/nodetube/nodetube/node_modules/node-sass/build/config.gypi
> npm ERR! gyp verb config.gypi checking for gypi file: /home/nodetube/nodetube/node_modules/node-sass/config.gypi
> npm ERR! gyp verb common.gypi checking for gypi file: /home/nodetube/nodetube/node_modules/node-sass/common.gypi
> npm ERR! gyp verb gyp gyp format was not specified; forcing "make"
> npm ERR! gyp info spawn /usr/bin/python2
> npm ERR! gyp info spawn args [
> npm ERR! gyp info spawn args   '/home/nodetube/nodetube/node_modules/node-gyp/gyp/gyp_main.py',
> npm ERR! gyp info spawn args   'binding.gyp',
> npm ERR! gyp info spawn args   '-f',
> npm ERR! gyp info spawn args   'make',
> npm ERR! gyp info spawn args   '-I',
> npm ERR! gyp info spawn args   '/home/nodetube/nodetube/node_modules/node-sass/build/config.gypi',
> npm ERR! gyp info spawn args   '-I',
> npm ERR! gyp info spawn args   '/home/nodetube/nodetube/node_modules/node-gyp/addon.gypi',
> npm ERR! gyp info spawn args   '-I',
> npm ERR! gyp info spawn args   '/home/nodetube/.node-gyp/21.6.1/include/node/common.gypi',
> npm ERR! gyp info spawn args   '-Dlibrary=shared_library',
> npm ERR! gyp info spawn args   '-Dvisibility=default',
> npm ERR! gyp info spawn args   '-Dnode_root_dir=/home/nodetube/.node-gyp/21.6.1',
> npm ERR! gyp info spawn args   '-Dnode_gyp_dir=/home/nodetube/nodetube/node_modules/node-gyp',
> npm ERR! gyp info spawn args   '-Dnode_lib_file=/home/nodetube/.node-gyp/21.6.1/<(target_arch)/node.lib',
> npm ERR! gyp info spawn args   '-Dmodule_root_dir=/home/nodetube/nodetube/node_modules/node-sass',
> npm ERR! gyp info spawn args   '-Dnode_engine=v8',
> npm ERR! gyp info spawn args   '--depth=.',
> npm ERR! gyp info spawn args   '--no-parallel',
> npm ERR! gyp info spawn args   '--generator-output',
> npm ERR! gyp info spawn args   'build',
> npm ERR! gyp info spawn args   '-Goutput_dir=.'
> npm ERR! gyp info spawn args ]
> npm ERR! Traceback (most recent call last):
> npm ERR!   File "/home/nodetube/nodetube/node_modules/node-gyp/gyp/gyp_main.py", line 16, in <module>
> npm ERR!     sys.exit(gyp.script_main())
> npm ERR!   File "/home/nodetube/nodetube/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 545, in script_main
> npm ERR!     return main(sys.argv[1:])
> npm ERR!   File "/home/nodetube/nodetube/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 538, in main
> npm ERR!     return gyp_main(args)
> npm ERR!   File "/home/nodetube/nodetube/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 514, in gyp_main
> npm ERR!     options.duplicate_basename_check)
> npm ERR!   File "/home/nodetube/nodetube/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 130, in Load
> npm ERR!     params['parallel'], params['root_targets'])
> npm ERR!   File "/home/nodetube/nodetube/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 2783, in Load
> npm ERR!     variables, includes, depth, check, True)
> npm ERR!   File "/home/nodetube/nodetube/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 399, in LoadTargetBuildFile
> npm ERR!     includes, True, check)
> npm ERR!   File "/home/nodetube/nodetube/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 271, in LoadOneBuildFile
> npm ERR!     aux_data, includes, check)
> npm ERR!   File "/home/nodetube/nodetube/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 308, in LoadBuildFileIncludesIntoDict
> npm ERR!     LoadOneBuildFile(include, data, aux_data, None, False, check),
> npm ERR!   File "/home/nodetube/nodetube/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 251, in LoadOneBuildFile
> npm ERR!     None)
> npm ERR!   File "/home/nodetube/.node-gyp/21.6.1/include/node/common.gypi", line 1
> npm ERR!     incremental linking
> npm ERR!                       ^
> npm ERR! SyntaxError: invalid syntax
> npm ERR! gyp ERR! configure error
> npm ERR! gyp ERR! stack Error: `gyp` failed with exit code: 1
> npm ERR! gyp ERR! stack     at ChildProcess.onCpExit (/home/nodetube/nodetube/node_modules/node-gyp/lib/configure.js:345:16)
> npm ERR! gyp ERR! stack     at ChildProcess.emit (node:events:519:28)
> npm ERR! gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:294:12)
> npm ERR! gyp ERR! System Linux 4.19.0-26-amd64
> npm ERR! gyp ERR! command "/usr/bin/node" "/home/nodetube/nodetube/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
> npm ERR! gyp ERR! cwd /home/nodetube/nodetube/node_modules/node-sass
> npm ERR! gyp ERR! node -v v21.6.1
> npm ERR! gyp ERR! node-gyp -v v3.8.0
> npm ERR! gyp ERR! not ok
> npm ERR! Build failed with error code: 1
> 
> npm ERR! A complete log of this run can be found in: /home/nodetube/.npm/_logs/2024-02-10T17_50_57_820Z-debug-0.log

Tail of debug.log:
> 7664 error gyp info spawn args ]
> 7664 error Traceback (most recent call last):
> 7664 error   File "/home/nodetube/nodetube/node_modules/node-gyp/gyp/gyp_main.py", line 16, in <module>
> 7664 error     sys.exit(gyp.script_main())
> 7664 error   File "/home/nodetube/nodetube/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 545, in script_main
> 7664 error     return main(sys.argv[1:])
> 7664 error   File "/home/nodetube/nodetube/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 538, in main
> 7664 error     return gyp_main(args)
> 7664 error   File "/home/nodetube/nodetube/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 514, in gyp_main
> 7664 error     options.duplicate_basename_check)
> 7664 error   File "/home/nodetube/nodetube/node_modules/node-gyp/gyp/pylib/gyp/__init__.py", line 130, in Load
> 7664 error     params['parallel'], params['root_targets'])
> 7664 error   File "/home/nodetube/nodetube/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 2783, in Load
> 7664 error     variables, includes, depth, check, True)
> 7664 error   File "/home/nodetube/nodetube/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 399, in LoadTargetBuildFile
> 7664 error     includes, True, check)
> 7664 error   File "/home/nodetube/nodetube/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 271, in LoadOneBuildFile
> 7664 error     aux_data, includes, check)
> 7664 error   File "/home/nodetube/nodetube/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 308, in LoadBuildFileIncludesIntoDict
> 7664 error     LoadOneBuildFile(include, data, aux_data, None, False, check),
> 7664 error   File "/home/nodetube/nodetube/node_modules/node-gyp/gyp/pylib/gyp/input.py", line 251, in LoadOneBuildFile
> 7664 error     None)
> 7664 error   File "/home/nodetube/.node-gyp/21.6.1/include/node/common.gypi", line 1
> 7664 error     incremental linking
> 7664 error                       ^
> 7664 error SyntaxError: invalid syntax
> 7664 error gyp ERR! configure error 
> 7664 error gyp ERR! stack Error: `gyp` failed with exit code: 1
> 7664 error gyp ERR! stack     at ChildProcess.onCpExit (/home/nodetube/nodetube/node_modules/node-gyp/lib/configure.js:345:16)
> 7664 error gyp ERR! stack     at ChildProcess.emit (node:events:519:28)
> 7664 error gyp ERR! stack     at ChildProcess._handle.onexit (node:internal/child_process:294:12)
> 7664 error gyp ERR! System Linux 4.19.0-26-amd64
> 7664 error gyp ERR! command "/usr/bin/node" "/home/nodetube/nodetube/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
> 7664 error gyp ERR! cwd /home/nodetube/nodetube/node_modules/node-sass
> 7664 error gyp ERR! node -v v21.6.1
> 7664 error gyp ERR! node-gyp -v v3.8.0
> 7664 error gyp ERR! not ok 
> 7664 error Build failed with error code: 1
> 7665 verbose exit 1
> 7666 timing npm Completed in 360979ms
> 7667 verbose unfinished npm timer reify 1707587458218
> 7668 verbose unfinished npm timer reify:build 1707587807279
> 7669 verbose unfinished npm timer build 1707587807286
> 7670 verbose unfinished npm timer build:deps 1707587807287
> 7671 verbose unfinished npm timer build:run:postinstall 1707587815673
> 7672 verbose unfinished npm timer build:run:postinstall:node_modules/node-sass 1707587815766
> 7673 verbose code 1
> 7674 error A complete log of this run can be found in: /home/nodetube/.npm/_logs/2024-02-10T17_50_57_820Z-debug-0.log
> 
[2024-02-10T17_50_57_820Z-debug-0.log](https://github.com/mayeaux/nodetube/files/14230108/2024-02-10T17_50_57_820Z-debug-0.log)

**Comment by Adi-18** [comment]
Not important anymore. I found a competing product.

**Comment by alejandroxin93** [comment]
> Not important anymore. I found a competing product.

Hi, what had you found?

**Comment by Tiritibambix** [comment]
> Not important anymore. I found a competing product.

Hello. What did you find ?
